### ISSUE TITLE
Doesn't work on PHP8+ for standalone (non-laravel) apps

### ISSUE THREAD

**Issue by aleemb** [formers/former#614]
(new issue since #611 is stale)

Former is broken on PHP8+ standalone installs and throws the error:

```
Uncaught Illuminate\Contracts\Container\BindingResolutionException: Target [Illuminate\Routing\RouteCollectionInterface] is not instantiable while building [Illuminate\Routing\UrlGenerator]
```

I found the quick fix is as follows, however, I am not familiar with the framework to do this proper. The fix that works for me is inside FormerServicesProvider.php I add the following in bindCoreClasses under the Core Classes comment:

		$app->bindIf(
			\Illuminate\Routing\RouteCollectionInterface::class,
			\Illuminate\Routing\RouteCollection::class
		);

Trying `$app->bindIf('routing', \Illuminate\Routing\RouteCollection::class);` didn't work, however.

Hope this can be fixed in the repo so Former can once again be used outside of Laravel (when using PHP8+). This is the only thing preventing that use-case right now for anyone using it outside of Laravel, myself included.

**Comment by stayallive** [comment]
You mention outside Laravel but it looks like you are still using Illuminate components.

Can you share bit more of the stacktrace so we know what Former code specifically catches this?

I doubt this has anything to do with the PHP version though, would assume this behaves the same on every PHP version and if this works on other versions it's because other dependency versions have changes.

**Comment by ehsanquddusi** [comment]
Facing same issue while using this library outside Laravel with CodeIgniter. I am also using some Illuminate libraries including `illuminate/database`, `illuminate/view` on `v11`. Here is the error I am getting.

This error is generated on both `4.*` & `5.*` versions of `Former` library.

![image](https://github.com/user-attachments/assets/dac08d8d-999f-440d-ab78-2d7f17c170e6)

**Comment by aleemb** [comment]
@stayallive  here's the stack trace that still persists with 5.1. and I am not using Laravel.

1. **Laravel's Container:** The Former package uses Laravel's Dependency Injection container (illuminate/container) to manage its objects and dependencies.

2. **Laravel's URL Generator**: To create the action attribute for a form (e.g., `<form action="/submit">)`, Former asks the container for Laravel's UrlGenerator service.

3. **Missing Router**: The UrlGenerator needs a list of all the application's routes to create URLs. It gets this from an object that implements the RouteCollectionInterface.

Here's the full stack trace:

```
Fatal error:
Uncaught Illuminate\Contracts\Container\BindingResolutionException: Target [Illuminate\Routing\RouteCollectionInterface] is not
instantiable while building [Illuminate\Routing\UrlGenerator]. in /var/www/example.com/vendor/illuminate/container/Container.php:1126
--
Stack trace:
#0 /var/www/example.com/vendor/illuminate/container/Container.php(921): Illuminate\Container\Container->notInstantiable()
#1 /var/www/example.com/vendor/illuminate/container/Container.php(795): Illuminate\Container\Container->build()
#2 /var/www/example.com/vendor/illuminate/container/Container.php(731): Illuminate\Container\Container->resolve()
#3 /var/www/example.com/vendor/illuminate/container/Container.php(1066): Illuminate\Container\Container->make()
#4 /var/www/example.com/vendor/illuminate/container/Container.php(982): Illuminate\Container\Container->resolveClass()
#5 /var/www/example.com/vendor/illuminate/container/Container.php(943): Illuminate\Container\Container->resolveDependencies()
#6 /var/www/example.com/vendor/illuminate/container/Container.php(795): Illuminate\Container\Container->build()
#7 /var/www/example.com/vendor/illuminate/container/Container.php(297): Illuminate\Container\Container->resolve()
#8 /var/www/example.com/vendor/illuminate/container/Container.php(908): Illuminate\Container\Container->Illuminate\Container\{closure}()
#9 /var/www/example.com/vendor/illuminate/container/Container.php(795): Illuminate\Container\Container->build()
#10 /var/www/example.com/vendor/illuminate/container/Container.php(731): Illuminate\Container\Container->resolve()
#11 /var/www/example.com/vendor/illuminate/container/Container.php(1454): Illuminate\Container\Container->make()
#12 /var/www/example.com/vendor/anahkiasen/former/src/Former/MethodDispatcher.php(126): Illuminate\Container\Container->offsetGet()
#13 /var/www/example.com/vendor/anahkiasen/former/src/Former/Former.php(128): Former\MethodDispatcher->toForm()
#14 /var/www/example.com/vendor/illuminate/support/Facades/Facade.php(355): Former\Former->__call()
#15 /var/www/example.com/apps/english/views/payment/index.php(25): Illuminate\Support\Facades\Facade::__callStatic()
#16 [internal function]: Phalcon\Mvc\View\Engine\Php->render()
#17 [internal function]: Phalcon\Mvc\View->engineRender()
#18 [internal function]: Phalcon\Mvc\View->processRender()
#19 [internal function]: Phalcon\Mvc\View->render()
#20 /var/www/example.com/apps/shared/lib/Mvc/View.php(235): call_user_func_array()
#21 [internal function]: Compunode\Lib\Mvc\View->render()
#22 /var/www/example.com/public/shared/index.php(56): Phalcon\Mvc\Application->handle()
#23 /var/www/example.com/public/english/index.php(3): require_once('...')
#24 {main}
thrown in <b>/var/www/example.com/vendor/illuminate/container/Container.php</b> on line <b>1126</b><br />
```
